namespace HollowKnightNoAreaTransitions.Maps;

public class Silksong
{
    public static readonly ChunkMap Map = MergeGeneratedChunksAndManualEdits(
        Silksong_AutoGenerated.Chunks,
        [
            new()
            {
                SceneName = "Bonetown",
                Colliders = [new(182f, -6f, 1f, 7f), new(189f, -6f, 1f, 7f)],
                OnLoad = scene =>
                {
                    // TODO: Fix lift position (it is controlled by FSM)
                    // Hide collider blocking entrance to town
                    var toHide = new string[][]
                    {
                        ["Steep Slope"],
                        ["terrain collider (6)"],
                        ["TileMap Render Data", "Scenemap", "Chunk 2 9"],
                    };
                    foreach (var path in toHide)
                        Utils.Unity.FindGameObjectByPath(scene, path).SetActive(false);
                },
            },
            new()
            {
                SceneName = "Bone_01",
                OnLoad = scene =>
                {
                    var toHide = new string[][]
                    {
                        ["TileMap Render Data", "Scenemap", "Chunk 2 0"],
                    };
                    foreach (var path in toHide)
                        Utils.Unity.FindGameObjectByPath(scene, path).SetActive(false);

                    Utils.Tilemap.ClampColliderPoints(
                        scene,
                        ["Roof Collider (33)"],
                        p => new(Mathf.Min(p.x, 27f), p.y)
                    );
                },
            },
            new()
            {
                SceneName = "Bone_01b",
                OnLoad = scene =>
                {
                    var toHide = new string[][]
                    {
                        ["Masks"],
                        ["TileMap Render Data", "Scenemap", "Chunk 0 0"],
                        ["TileMap Render Data", "Scenemap", "Chunk 0 1"],
                        ["TileMap Render Data", "Scenemap", "Chunk 1 1"],
                    };
                    foreach (var path in toHide)
                        Utils.Unity.FindGameObjectByPath(scene, path).SetActive(false);
                },
            },
            new()
            {
                SceneName = "Bone_01c",
                // TODO: Stop collider intersecting room to left
                OnLoad = scene =>
                {
                    var toHide = new string[][]
                    {
                        ["TileMap Render Data", "Scenemap", "Chunk 0 0"],
                        ["TileMap Render Data", "Scenemap", "Chunk 0 1"],
                        ["TileMap Render Data", "Scenemap", "Chunk 0 2"],
                        ["TileMap Render Data", "Scenemap", "Chunk 0 3"],
                        ["TileMap Render Data", "Scenemap", "Chunk 1 0"],
                        ["TileMap Render Data", "Scenemap", "Chunk 1 1"],
                        ["TileMap Render Data", "Scenemap", "Chunk 1 2"],
                        ["TileMap Render Data", "Scenemap", "Chunk 1 3"],
                        ["TileMap Render Data", "Scenemap", "Chunk 2 0"],
                        ["TileMap Render Data", "Scenemap", "Chunk 2 1"],
                        ["TileMap Render Data", "Scenemap", "Chunk 2 2"],
                        ["TileMap Render Data", "Scenemap", "Chunk 2 3"],
                        ["msk_generic_soft"],
                        ["msk_generic_soft (1)"],
                        ["msk_generic_soft (2)"],
                        ["pipe_mask_02"],
                        ["pipe_mask_02 (1)"],
                        ["pipe_mask_02 (2)"],
                        ["pipe_mask_02 (3)"],
                        ["pipe_mask_02 (4)"],
                        ["pipe_mask_02 (5)"],
                        ["pipe_mask_02 (6)"],
                        ["pipe_mask_02 (7)"],
                        ["pipe_mask_02 (8)"],
                        ["fog (5)"],
                        ["fog (6)"],
                        ["fog (9)"],
                        ["SceneBorder"],
                        ["SceneBorder (1)"],
                        ["terrain collider non slider"],
                        ["terrain collider non slider (1)"],
                        ["terrain collider non slider (2)"],
                        ["Group", "black_fader_moon (10)"],
                        ["Group", "black_fader_moon (11)"],
                        ["Group", "black_fader_moon (12)"],
                        ["Group", "black_fader_moon (13)"],
                        ["Group", "black_fader_moon (14)"],
                        ["Group", "black_fader_moon (15)"],
                        ["Group (1)", "black_fader_moon (9)"],
                        ["Group (1)", "black_fader_moon (10)"],
                        ["Group (1)", "black_fader_moon (11)"],
                    };
                    foreach (var path in toHide)
                        Utils.Unity.FindGameObjectByPath(scene, path).SetActive(false);

                    Utils.Tilemap.ClampColliderPoints(
                        scene,
                        ["Roof Collider (33)"],
                        p => new(Mathf.Clamp(p.x, 26f, 95f), p.y)
                    );
                },
            },
            new()
            {
                SceneName = "Bone_02",
                OnLoad = scene =>
                {
                    var toHide = new string[][]
                    {
                        ["terrain collider non slider"],
                        ["terrain collider non slider (1)"],
                        ["terrain collider non slider (2)"],
                        ["Group (2)", "black_fader_moon (8)"],
                        ["Group (2)", "black_fader_moon (9)"],
                        ["Group (2)", "black_fader_moon (11)"],
                    };
                    foreach (var path in toHide)
                        Utils.Unity.FindGameObjectByPath(scene, path).SetActive(false);

                    Utils.Tilemap.ClampColliderPoints(
                        scene,
                        ["Roof Collider (10)"],
                        p => new(Mathf.Max(p.x, -9f), Math.Max(p.y, -6.5f))
                    );

                    Utils.Tilemap.ClampColliderPoints(
                        scene,
                        ["Roof Collider"],
                        p => new(p.x, Math.Min(p.y, 10f))
                    );
                },
            },
            new()
            {
                SceneName = "Bone_09",
                OnLoad = scene =>
                {
                    var toHide = new string[][] { ["SC_0047_sc_door (2)"] };
                    foreach (var path in toHide)
                        Utils.Unity.FindGameObjectByPath(scene, path).SetActive(false);

                    Utils.Tilemap.ClampColliderPoints(
                        scene,
                        ["Roof Collider_Basic (10)"],
                        p => new(Mathf.Min(p.x, 14f), Math.Max(p.y, -4f))
                    );
                },
            },
            new()
            {
                SceneName = "Dock_01",
                OnLoad = scene =>
                {
                    var toHide = new string[][] { ["terrain collider"] };
                    foreach (var path in toHide)
                        Utils.Unity.FindGameObjectByPath(scene, path).SetActive(false);
                },
            },
            new()
            {
                SceneName = "Dock_08",
                OnLoad = scene =>
                {
                    var toHide = new string[][] { ["Remasker New"] };
                    foreach (var path in toHide)
                        Utils.Unity.FindGameObjectByPath(scene, path).SetActive(false);
                },
            },
            new()
            {
                SceneName = "Tut_01",
                OnLoad = scene =>
                {
                    var toHide = new string[][]
                    {
                        ["Song Gate Tinker"], // TODO: What is this? Is it needed?
                        ["TileMap Render Data", "Scenemap", "Chunk 1 3"],
                        ["TileMap Render Data", "Scenemap", "Chunk 2 3"],
                        ["TileMap Render Data", "Scenemap", "Chunk 3 3"],
                        ["msk_generic_soft"],
                        ["msk_generic_soft (1)"],
                        ["SceneBorder"],
                        ["SceneBorder (1)"],
                        ["Group", "pipe_mask_02 (4)"],
                        ["Group (2)"],
                    };
                    foreach (var path in toHide)
                        Utils.Unity.FindGameObjectByPath(scene, path).SetActive(false);

                    // Remove the black coverings behind the arch but keep the arch itself
                    var boneArch = Utils.Unity.FindGameObjectByPath(
                        scene,
                        ["bone_church_arch (7)"]
                    );
                    for (int i = 6; i < boneArch.transform.childCount; i++)
                        boneArch.transform.GetChild(i).gameObject.SetActive(false);
                },
            },
            new()
            {
                SceneName = "Tut_01b",
                OnLoad = scene =>
                {
                    var toHide = new string[][]
                    {
                        ["SceneBorder"],
                        ["TileMap Render Data", "Scenemap", "Chunk 0 0"],
                        ["TileMap Render Data", "Scenemap", "Chunk 0 1"],
                        ["TileMap Render Data", "Scenemap", "Chunk 0 2"],
                        ["TileMap Render Data", "Scenemap", "Chunk 0 3"],
                        ["TileMap Render Data", "Scenemap", "Chunk 0 4"],
                        ["TileMap Render Data", "Scenemap", "Chunk 1 0"],
                        ["TileMap Render Data", "Scenemap", "Chunk 1 1"],
                        ["TileMap Render Data", "Scenemap", "Chunk 2 0"],
                        ["TileMap Render Data", "Scenemap", "Chunk 2 1"],
                        ["TileMap Render Data", "Scenemap", "Chunk 3 0"],
                        ["TileMap Render Data", "Scenemap", "Chunk 3 1"],
                        ["msk_generic_soft"],
                        ["msk_generic_soft (1)"],
                    };
                    foreach (var path in toHide)
                        Utils.Unity.FindGameObjectByPath(scene, path).SetActive(false);
                },
            },
            new()
            {
                SceneName = "Tut_03",
                OnLoad = scene =>
                {
                    var toHide = new string[][]
                    {
                        ["church front collider"],
                        ["bone_church_arch (4)"],
                        ["bone_church_04 (57)"],
                    };
                    foreach (var path in toHide)
                        Utils.Unity.FindGameObjectByPath(scene, path).SetActive(false);
                },
            },
            new()
            {
                SceneName = "Weave_04",
                OnLoad = scene =>
                {
                    var toHide = new string[][]
                    {
                        ["terrain collider"],
                        ["terrain collider (1)"],
                        ["terrain collider (2)"],
                        ["terrain collider (3)"],
                        ["terrain collider (4)"],
                        ["terrain collider (5)"],
                        ["terrain collider (6)"],
                        ["terrain collider (7)"],
                        ["terrain collider (8)"],
                        ["terrain collider (9)"],
                        ["terrain collider (10)"],
                        ["terrain collider (13)"],
                        ["TileMap Render Data", "Scenemap", "Chunk 0 0"],
                        ["TileMap Render Data", "Scenemap", "Chunk 0 1"],
                        ["TileMap Render Data", "Scenemap", "Chunk 0 2"],
                        ["TileMap Render Data", "Scenemap", "Chunk 1 0"],
                        ["TileMap Render Data", "Scenemap", "Chunk 1 1"],
                        ["TileMap Render Data", "Scenemap", "Chunk 1 2"],
                        ["Weaver Servitor (2)"],
                    };
                    foreach (var path in toHide)
                        Utils.Unity.FindGameObjectByPath(scene, path).SetActive(false);
                },
            },
            new()
            {
                SceneName = "Weave_11",
                OnLoad = scene =>
                {
                    var toHide = new string[][] { ["Remasker New Sharp Ultra"] };
                    foreach (var path in toHide)
                        Utils.Unity.FindGameObjectByPath(scene, path).SetActive(false);

                    Utils.Tilemap.ClampColliderPoints(
                        scene,
                        ["Roof Collider_Basic"],
                        p => new(p.x, Math.Min(p.y, 12f))
                    );

                    var boxColsToShrink = new string[][]
                    {
                        ["terrain collider (2)"],
                        ["terrain collider (3)"],
                    };
                    var amountToLower = 8f;
                    foreach (var path in boxColsToShrink)
                    {
                        var tr = Utils.Unity.FindGameObjectByPath(scene, path).transform;
                        tr.localScale = new(
                            tr.localScale.x,
                            tr.localScale.y - amountToLower,
                            tr.localScale.z
                        );
                        tr.localPosition = new(
                            tr.localPosition.x,
                            tr.localPosition.y - amountToLower / 2f,
                            tr.localPosition.z
                        );
                    }
                },
            },
            new()
            {
                SceneName = "Weave_14",
                OnLoad = scene =>
                {
                    Utils.Tilemap.ClampColliderPoints(
                        scene,
                        ["Roof Collider_Basic (1)"],
                        p => new(p.x, Math.Min(p.y, 7f))
                    );
                },
            },
        ]
    );

    private static ChunkMap MergeGeneratedChunksAndManualEdits(
        List<Chunk> autoGeneratedChunks,
        List<Chunk> manualEdits
    )
    {
        var mergedChunks = autoGeneratedChunks.ToDictionary(c => c.SceneName);
        foreach (var chunk in manualEdits)
        {
            if (mergedChunks.TryGetValue(chunk.SceneName, out var existingChunk))
            {
                if (chunk.Colliders != null)
                    existingChunk.Colliders =
                    [
                        .. existingChunk.Colliders ?? [],
                        .. chunk.Colliders,
                    ];
                if (chunk.OnLoad != null)
                    existingChunk.OnLoad = chunk.OnLoad;
            }
            else
            {
                mergedChunks[chunk.SceneName] = chunk;
            }
        }
        return new([.. mergedChunks.Values]);
    }
}
